
name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v2
    - uses: dawidd6/action-debian-package@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libgee-0.8-dev libjson-glib-dev libgranite-dev libgtk-3-dev libgtksourceview-3.0-dev libvala-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  debian:
    runs-on: ubuntu-latest
    steps:
    - name: Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        artifacts_directory: output # optional, relative to workspace directory

  flatpak:

    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "manuscript.flatpak"
        manifest-path: "flatpak/com.github.sixpounder.manuscript.yml"

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: io.elementary.vala-lint -d .
