
name: CI

on:
  push:
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libarchive-dev libgee-0.8-dev libjson-glib-dev libgranite-dev libgtk-3-dev libgtksourceview-3.0-dev libvala-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:

    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "manuscript.flatpak"
        manifest-path: "flatpak/com.github.sixpounder.manuscript.yml"
