name: Meson build

on: push

jobs:
  meson-builder:
    name: "Meson"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
